### ISSUE TITLE
Feature: User can view current games and navigate website

### ISSUE THREAD

**Issue by leejaejoseph** [leejaejoseph/LCS-Schedule#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view current on-going games and navigate the website with menu-bar
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will click the games within the schedules tab and it will open a new page showing the status of the current games or future games.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![DeskTop](https://user-images.githubusercontent.com/116613246/213780003-742c4572-8009-4e3d-a6e5-2fa26e1caaa6.png)
![Mobile](https://user-images.githubusercontent.com/116613246/213780073-ef6bfb2c-1ed4-4bcb-9167-4f1ba2e5b7b0.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] Set the layout for the current-games page with:
  - [x] mobile layout set up first and moving seamlessly to desktop. 
  - [x] create similar layout to figma pictures where user can:
    - [x] grab information regarding links to where the user can watch current games and create corresponding button to platform.
    - [x] see current game status, winner, series information, and team win loss
- [x] make the schedules in the schedule page link to a render of the current game referenced.
- [x] add menu bar on top for mobile and desktop.
- [x] add anchors that link to the corresponding pages
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
